{{- if and .Values.serviceAccount.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stdapp.saname" . }}
  labels:
    {{- include "stdapp.labels" . | nindent 4 }}
  annotations:
    {{- range $name, $annotation := .Values.serviceAccount.annotations }}
    {{ $name }}: {{ $annotation | quote }}
    {{- end }}
{{- end }}
